name: Build and deploy container app to Azure VM - stun-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "13.69.253.214"
        username: "stunusername"
        password: "Stunpassword1"
        script: whoami