name: Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # - name: executing remote ssh commands using password
      # uses: appleboy/ssh-action@master
      # with:
        # host: ${{ secrets.VM_IP }}
        # username: ${{ secrets.VM_USERNAME }}
        # password: ${{ secrets.VM_PASSWORD }}
        # script: sudo ufw allow 8080 && cd IDATT2104-Project && git pull origin && sudo make deploy < /dev/null > /tmp/mylogfile 2>&1 & echo "deployed" && ls -a && exit
        
    - name: Deploy to Azure VM
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo ufw allow 8080
          cd IDATT2104-Project
          git pull origin
          sudo make deploy < /dev/null > /tmp/mylogfile 2>&1 &
          echo "deployed"
        host: ${{ secrets.VM_IP }}
        user: ${{ secrets.VM_USERNAME }}
        pass : ${{ secrets.VM_PASSWORD }}
        key: ""
        args: "-tt -vvv"
